export const englishBookSchedule = [
  {
    week: 1,
    chapter: 'Chapter 1',
    title: 'Present and Past; Simple and Progressive',
    pages: 'pp. 1–24',
    exercises: ['Ex. 1–6', 'Ex. 7–12', 'Ex. 13–18', 'Ex. 19–25', 'Ex. 26–30', 'Ex. 31–37', 'Review + mini test'],
  },
  {
    week: 2,
    chapter: 'Chapter 2',
    title: 'Perfect and Perfect Progressive Tenses',
    pages: 'pp. 25–52',
    exercises: ['Ex. 1–5', 'Ex. 6–10', 'Ex. 11–15', 'Ex. 16–20', 'Ex. 21–25', 'Ex. 26–29', 'Review + mini test'],
  },
  {
    week: 3,
    chapter: 'Chapter 3',
    title: 'Future Time',
    pages: 'pp. 53–69',
    exercises: ['Ex. 1–6', 'Ex. 7–12', 'Ex. 13–17', 'Ex. 18–22', 'Ex. 23–27', 'Ex. 28–29', 'Review + mini test'],
  },
  {
    week: 4,
    chapter: 'Chapter 4',
    title: 'Review of Verb Tenses',
    pages: 'pp. 70–77',
    exercises: ['Ex. 1–3', 'Ex. 4–6', 'Ex. 7–9', 'Ex. 10–12', 'Ex. 13–16', 'Redo lỗi Chapter 1–3', 'Checkpoint 12 thì'],
  },
  {
    week: 5,
    chapter: 'Chapters 5–6',
    title: 'Subject–Verb Agreement + Nouns',
    pages: 'pp. 78–121',
    exercises: ['Ch. 5 Ex. 1–6', 'Ch. 5 Ex. 7–12', 'Ch. 5 Ex. 13–18', 'Ch. 5 Review Ex. 19–26', 'Ch. 6 Ex. 1–6', 'Ch. 6 Ex. 7–13', 'Review + mini test'],
  },
  {
    week: 6,
    chapter: 'Chapters 7–8',
    title: 'Articles + Pronouns',
    pages: 'pp. 122–160',
    exercises: ['Ch. 7 Ex. 1–6', 'Ch. 7 Ex. 7–12', 'Ch. 7 Ex. 13–18', 'Ch. 8 Ex. 1–6', 'Ch. 8 Ex. 7–12', 'Ch. 8 Ex. 13–16', 'Review + mini test'],
  },
  {
    week: 7,
    chapter: 'Chapters 9–10',
    title: 'Modals, Part 1–2',
    pages: 'pp. 161–214',
    exercises: ['Ch. 9 Ex. 1–6', 'Ch. 9 Ex. 7–12', 'Ch. 9 Ex. 13–18', 'Ch. 10 Ex. 1–6', 'Ch. 10 Ex. 7–12', 'Ch. 10 Ex. 13–16', 'Review + mini test'],
  },
  {
    week: 8,
    chapter: 'Chapters 11–12',
    title: 'The Passive + Noun Clauses',
    pages: 'pp. 215–271',
    exercises: ['Ch. 11 Ex. 1–6', 'Ch. 11 Ex. 7–12', 'Ch. 11 Ex. 13–18', 'Ch. 12 Ex. 1–6', 'Ch. 12 Ex. 7–12', 'Ch. 12 Ex. 13–16', 'Review + mini test'],
  },
  {
    week: 9,
    chapter: 'Chapters 13–14',
    title: 'Adjective Clauses + Gerunds and Infinitives, Part 1',
    pages: 'pp. 272–333',
    exercises: ['Ch. 13 Ex. 1–6', 'Ch. 13 Ex. 7–12', 'Ch. 13 Ex. 13–18', 'Ch. 14 Ex. 1–6', 'Ch. 14 Ex. 7–12', 'Ch. 14 Ex. 13–17', 'Review + mini test'],
  },
  {
    week: 10,
    chapter: 'Chapters 15–16',
    title: 'Gerunds and Infinitives, Part 2 + Conjunctions',
    pages: 'pp. 334–369',
    exercises: ['Ch. 15 Ex. 1–6', 'Ch. 15 Ex. 7–12', 'Ch. 15 Ex. 13–17', 'Ch. 16 Ex. 1–6', 'Ch. 16 Ex. 7–12', 'Ch. 16 Ex. 13–21', 'Review + mini test'],
  },
  {
    week: 11,
    chapter: 'Chapters 17–19',
    title: 'Adverb Clauses + Reduction + Cause and Effect',
    pages: 'pp. 370–425',
    exercises: ['Ch. 17 Ex. 1–6', 'Ch. 17 Ex. 7–12', 'Ch. 18 Ex. 1–6', 'Ch. 18 Ex. 7–12', 'Ch. 19 Ex. 1–6', 'Ch. 19 Ex. 7–12', 'Review + mini test'],
  },
  {
    week: 12,
    chapter: 'Chapter 20',
    title: 'Conditional Sentences and Wishes',
    pages: 'pp. 426–461',
    exercises: ['Ex. 1–8', 'Ex. 9–19', 'Ex. 20–25', 'Ex. 26–33', 'Ex. 34–41', 'Ex. 42–50', 'Final test + maintenance plan'],
  },
]

export const quizSets = [
  {
    id: 'chapter-1-foundation',
    label: 'Checkpoint 01 · Chapter 1',
    title: 'Present Simple, Present Progressive và Past Simple',
    source: 'Dựa trên Student Book Chapter 1, Ex. 3, 8, 11, 17, 22, 29 và Answer Key pp. 208–214.',
    questions: [
      {
        id: 'ch1-1',
        type: 'choice',
        prompt: 'My sister ___ to work by bus every day.',
        options: ['go', 'goes', 'is going'],
        answer: 'goes',
        explanation: '“Every day” diễn tả thói quen nên dùng Present Simple; chủ ngữ số ít cần V-s/es.',
      },
      {
        id: 'ch1-2',
        type: 'choice',
        prompt: 'Listen! The baby ___.',
        options: ['cries', 'is crying', 'cry'],
        answer: 'is crying',
        explanation: '“Listen!” báo hiệu hành động đang xảy ra ngay lúc nói → am/is/are + V-ing.',
      },
      {
        id: 'ch1-3',
        type: 'text',
        prompt: 'I ___ (not / know) Sami’s wife.',
        answer: ["don't know", 'do not know'],
        displayAnswer: "don't know",
        explanation: 'Know là stative verb. Phủ định Present Simple với I dùng do not/don’t + động từ nguyên mẫu.',
      },
      {
        id: 'ch1-4',
        type: 'choice',
        prompt: 'When I turned the key, the car ___.',
        options: ["doesn't start", "didn't start", "wasn't starting"],
        answer: "didn't start",
        explanation: 'Sự việc đã kết thúc trong quá khứ → Past Simple: did not + V nguyên mẫu.',
      },
      {
        id: 'ch1-5',
        type: 'choice',
        prompt: 'A few children ___ some pictures while the teacher was talking.',
        options: ['draw', 'drew', 'were drawing'],
        answer: 'drew',
        explanation: 'Hành động ngắn xen vào nền “was talking” dùng Past Simple: drew.',
      },
      {
        id: 'ch1-6',
        type: 'choice',
        prompt: 'The sun ___ in the east.',
        options: ['is rising', 'rises', 'rose'],
        answer: 'rises',
        explanation: 'Sự thật hiển nhiên dùng Present Simple.',
      },
      {
        id: 'ch1-7',
        type: 'text',
        prompt: 'Right now, I ___ (work) on my English.',
        answer: 'am working',
        explanation: '“Right now” → Present Progressive: am + V-ing.',
      },
      {
        id: 'ch1-8',
        type: 'choice',
        prompt: 'Which pairing best describes a background action interrupted by a short event?',
        options: ['Present Simple + Present Progressive', 'Past Progressive + Past Simple', 'Past Simple + Present Perfect'],
        answer: 'Past Progressive + Past Simple',
        explanation: 'Past Progressive tạo bối cảnh; Past Simple diễn tả sự kiện chen vào.',
      },
    ],
  },
  {
    id: 'chapter-2-perfect',
    label: 'Checkpoint 02 · Chapter 2',
    title: 'Perfect và Perfect Progressive',
    source: 'Dựa trên Student Book Chapter 2, Ex. 3, 10, 17, 23, 29 và Answer Key pp. 215–222.',
    questions: [
      {
        id: 'ch2-1',
        type: 'choice',
        prompt: 'I ___ this book three times.',
        options: ['read', 'have read', 'am reading'],
        answer: 'have read',
        explanation: 'Hành động lặp lại đến hiện tại, không có mốc quá khứ cụ thể → Present Perfect.',
      },
      {
        id: 'ch2-2',
        type: 'choice',
        prompt: 'She has been studying English ___ two years.',
        options: ['since', 'for', 'already'],
        answer: 'for',
        explanation: 'For đi với khoảng thời gian; since đi với mốc bắt đầu.',
      },
      {
        id: 'ch2-3',
        type: 'text',
        prompt: 'They ___ (wait) for the bus since 7:00.',
        answer: 'have been waiting',
        explanation: 'Hành động bắt đầu trong quá khứ và còn tiếp diễn, nhấn mạnh quá trình → Present Perfect Progressive.',
      },
      {
        id: 'ch2-4',
        type: 'choice',
        prompt: 'By the time we arrived, the movie ___.',
        options: ['has started', 'had started', 'was starting'],
        answer: 'had started',
        explanation: 'Một hành động xảy ra trước một mốc quá khứ khác → Past Perfect.',
      },
      {
        id: 'ch2-5',
        type: 'choice',
        prompt: 'Have you finished your homework ___?',
        options: ['yet', 'since', 'for'],
        answer: 'yet',
        explanation: 'Yet thường dùng trong câu hỏi/phủ định Present Perfect để hỏi việc đã hoàn tất chưa.',
      },
      {
        id: 'ch2-6',
        type: 'text',
        prompt: 'He ___ (work) there since he graduated.',
        answer: ['has worked', 'has been working'],
        displayAnswer: 'has worked / has been working',
        explanation: 'Cả hai đều có thể đúng: has worked nhấn факт/kết quả; has been working nhấn quá trình kéo dài.',
      },
    ],
  },
  {
    id: 'chapter-3-future',
    label: 'Checkpoint 03 · Chapter 3',
    title: 'Future Simple, Future Progressive và Future Perfect',
    source: 'Dựa trên Student Book Chapter 3, Ex. 2, 11, 16, 23, 29 và Answer Key pp. 223–229.',
    questions: [
      {
        id: 'ch3-1',
        type: 'choice',
        prompt: 'The phone is ringing. I ___ it.',
        options: ['answer', 'will answer', 'am answering'],
        answer: 'will answer',
        explanation: 'Quyết định đưa ra ngay lúc nói → will + V.',
      },
      {
        id: 'ch3-2',
        type: 'choice',
        prompt: 'This time tomorrow, I ___ to Da Nang.',
        options: ['will drive', 'will be driving', 'have driven'],
        answer: 'will be driving',
        explanation: 'Hành động đang diễn ra tại một mốc tương lai → Future Progressive.',
      },
      {
        id: 'ch3-3',
        type: 'text',
        prompt: 'By Friday, we ___ (finish) the first draft.',
        answer: 'will have finished',
        explanation: 'Hoàn tất trước một mốc tương lai → will have + V3.',
      },
      {
        id: 'ch3-4',
        type: 'choice',
        prompt: 'Look at those clouds! It ___.',
        options: ['will rain', 'is going to rain', 'rains'],
        answer: 'is going to rain',
        explanation: 'Dự đoán dựa trên bằng chứng hiện tại → be going to.',
      },
      {
        id: 'ch3-5',
        type: 'choice',
        prompt: 'At 8 p.m. tonight, she ___ for her exam.',
        options: ['will study', 'will be studying', 'studies'],
        answer: 'will be studying',
        explanation: 'Có mốc cụ thể và hành động đang diễn ra ở mốc đó → Future Progressive.',
      },
      {
        id: 'ch3-6',
        type: 'choice',
        prompt: 'By next month, I ___ English for one year.',
        options: ['will learn', 'will have learned', 'will have been learning'],
        answer: 'will have been learning',
        explanation: 'Nhấn mạnh khoảng thời gian kéo dài đến một mốc tương lai → Future Perfect Progressive.',
      },
    ],
  },
  {
    id: 'chapter-4-review',
    label: 'Checkpoint 04 · Chapters 1–3',
    title: 'Mixed review · chọn thì theo timeline',
    source: 'Dựa trên Student Book Chapter 4 Review, Ex. 1–16 và Answer Key pp. 229–234.',
    questions: [
      {
        id: 'ch4-1',
        type: 'choice',
        prompt: 'I ___ my report, so I can relax now.',
        options: ['finish', 'have finished', 'was finishing'],
        answer: 'have finished',
        explanation: 'Kết quả vừa hoàn tất còn liên quan hiện tại → Present Perfect.',
      },
      {
        id: 'ch4-2',
        type: 'choice',
        prompt: 'While I ___ dinner, my friend called.',
        options: ['cooked', 'was cooking', 'have cooked'],
        answer: 'was cooking',
        explanation: 'Hành động đang diễn ra làm nền cho sự kiện “called” → Past Progressive.',
      },
      {
        id: 'ch4-3',
        type: 'text',
        prompt: 'When we got to the station, the train ___ (leave).',
        answer: 'had left',
        explanation: 'Tàu rời đi trước mốc “we got” trong quá khứ → Past Perfect.',
      },
      {
        id: 'ch4-4',
        type: 'choice',
        prompt: 'By the end of this week, I ___ all Chapter 1 exercises.',
        options: ['complete', 'will have completed', 'am completing'],
        answer: 'will have completed',
        explanation: 'Hoàn tất trước mốc tương lai “by the end of this week” → Future Perfect.',
      },
      {
        id: 'ch4-5',
        type: 'choice',
        prompt: 'How long ___ you ___ English?',
        options: ['do / study', 'have / been studying', 'are / studying'],
        answer: 'have / been studying',
        explanation: 'How long + hành động bắt đầu trước và kéo dài đến hiện tại → Present Perfect Progressive.',
      },
      {
        id: 'ch4-6',
        type: 'choice',
        prompt: 'I think people ___ more flexible work in the future.',
        options: ['will want', 'are wanting', 'wanted'],
        answer: 'will want',
        explanation: 'Dự đoán về tương lai → will + V; want thường không dùng ở dạng progressive.',
      },
    ],
  },
]

